package org.milimail.messageRemoteServiceAPI.stubs;

/**
* _MessageSendListenerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/ClientServices.idl
* Tuesday, March 25, 2008 3:23:05 PM CET
*/

public class _MessageSendListenerStub extends org.omg.CORBA.portable.ObjectImpl implements MessageSendListener
{

  public void OnStop (String id, boolean success)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("OnStop", true);
                $out.write_string (id);
                $out.write_boolean (success);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                OnStop (id, success        );
            } finally {
                _releaseReply ($in);
            }
  } // OnStop

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MessageSendListener:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _MessageSendListenerStub
