package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Friday, June 13, 2008 3:22:41 PM CEST
*/

public interface AccountServiceOperations 
{
  CAccount[] GetAllAccounts () throws InternalServerException;
} // interface AccountServiceOperations
