package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Friday, June 13, 2008 3:22:41 PM CEST
*/

public interface AccountService extends AccountServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AccountService
