package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Thursday, June 12, 2008 11:49:38 AM CEST
*/

public interface AccountServiceOperations 
{
  CAccount[] GetAllAccounts () throws InternalServerException;
} // interface AccountServiceOperations
