package org.milimail.messageRemoteServiceAPI.stubs;

/**
* Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 14, 2008 12:14:15 PM CEST
*/

public final class Account implements org.omg.CORBA.portable.IDLEntity
{
  public String serverHostName = null;
  public String key = null;

  public Account ()
  {
  } // ctor

  public Account (String _serverHostName, String _key)
  {
    serverHostName = _serverHostName;
    key = _key;
  } // ctor

} // class Account
