package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 21, 2008 11:06:48 AM CEST
*/

public final class AccountServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AccountService value = null;

  public AccountServiceHolder ()
  {
  }

  public AccountServiceHolder (AccountService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AccountServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AccountServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AccountServiceHelper.type ();
  }

}
