package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 14, 2008 12:14:15 PM CEST
*/

public interface AccountService extends AccountServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AccountService
