package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Tuesday, May 13, 2008 4:03:40 PM CEST
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AccountHelper.type ();
  }

}
