package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 14, 2008 12:14:15 PM CEST
*/

public final class AccountsHolder implements org.omg.CORBA.portable.Streamable
{
  public Account value[] = null;

  public AccountsHolder ()
  {
  }

  public AccountsHolder (Account[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AccountsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AccountsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AccountsHelper.type ();
  }

}
