package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Tuesday, September 9, 2008 3:54:32 PM CEST
*/

public interface AccountServiceOperations 
{
  CAccount[] GetAllAccounts () throws CInternalServerException;
} // interface AccountServiceOperations
