package org.milimail.messageRemoteServiceAPI.stubs;

/**
* Attachment.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Thursday, June 12, 2008 11:49:38 AM CEST
*/

public final class Attachment implements org.omg.CORBA.portable.IDLEntity
{
  public String dirPath = null;
  public String fileName = null;
  public String mimeType = null;

  public Attachment ()
  {
  } // ctor

  public Attachment (String _dirPath, String _fileName, String _mimeType)
  {
    dirPath = _dirPath;
    fileName = _fileName;
    mimeType = _mimeType;
  } // ctor

} // class Attachment
