package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AttachmentsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 21, 2008 11:06:48 AM CEST
*/

abstract public class AttachmentsHelper
{
  private static String  _id = "IDL:Attachments:1.0";

  public static void insert (org.omg.CORBA.Any a, Attachment[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Attachment[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = AttachmentHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (AttachmentsHelper.id (), "Attachments", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Attachment[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Attachment value[] = null;
    int _len0 = istream.read_long ();
    value = new Attachment[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = AttachmentHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Attachment[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      AttachmentHelper.write (ostream, value[_i0]);
  }

}
