package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CAttachmentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Tuesday, September 9, 2008 3:54:32 PM CEST
*/

public final class CAttachmentHolder implements org.omg.CORBA.portable.Streamable
{
  public CAttachment value = null;

  public CAttachmentHolder ()
  {
  }

  public CAttachmentHolder (CAttachment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CAttachmentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CAttachmentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CAttachmentHelper.type ();
  }

}
