package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CDSNType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Thursday, September 4, 2008 2:33:40 PM CEST
*/

public final class CDSNType implements org.omg.CORBA.portable.IDLEntity
{
  public boolean isReturnFullHDRRequested = false;
  public boolean isOnSuccessRequested = false;
  public boolean isOnFailureRequested = false;
  public boolean isOnDelayRequested = false;
  public boolean isNeverRequested = false;

  public CDSNType ()
  {
  } // ctor

  public CDSNType (boolean _isReturnFullHDRRequested, boolean _isOnSuccessRequested, boolean _isOnFailureRequested, boolean _isOnDelayRequested, boolean _isNeverRequested)
  {
    isReturnFullHDRRequested = _isReturnFullHDRRequested;
    isOnSuccessRequested = _isOnSuccessRequested;
    isOnFailureRequested = _isOnFailureRequested;
    isOnDelayRequested = _isOnDelayRequested;
    isNeverRequested = _isNeverRequested;
  } // ctor

} // class CDSNType
