package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CFolderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Monday, September 22, 2008 6:24:12 PM CEST
*/

public final class CFolderHolder implements org.omg.CORBA.portable.Streamable
{
  public CFolder value = null;

  public CFolderHolder ()
  {
  }

  public CFolderHolder (CFolder initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CFolderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CFolderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CFolderHelper.type ();
  }

}
