package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Thursday, September 4, 2008 2:33:40 PM CEST
*/

public final class CHeader implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public String value = null;

  public CHeader ()
  {
  } // ctor

  public CHeader (String _key, String _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class CHeader
