package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 14, 2008 11:54:52 AM CEST
*/

public final class CHeader implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public String value = null;

  public CHeader ()
  {
  } // ctor

  public CHeader (String _key, String _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class CHeader
