package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CHeaderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Friday, September 19, 2008 6:32:29 PM CEST
*/

public final class CHeaderHolder implements org.omg.CORBA.portable.Streamable
{
  public CHeader value = null;

  public CHeaderHolder ()
  {
  }

  public CHeaderHolder (CHeader initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CHeaderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CHeaderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CHeaderHelper.type ();
  }

}
