package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CMessageHdr.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Friday, September 19, 2008 6:32:29 PM CEST
*/

public final class CMessageHdr implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;

  public CMessageHdr ()
  {
  } // ctor

  public CMessageHdr (String _id)
  {
    id = _id;
  } // ctor

} // class CMessageHdr
