package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CMessageHdr.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Monday, September 22, 2008 6:24:12 PM CEST
*/

public final class CMessageHdr implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String author = null;
  public String subject = null;
  public String recipients[] = null;
  public String ccRecipients[] = null;
  public String date = null;
  public String charset = null;
  public boolean isRead = false;
  public int size = (int)0;

  public CMessageHdr ()
  {
  } // ctor

  public CMessageHdr (String _id, String _author, String _subject, String[] _recipients, String[] _ccRecipients, String _date, String _charset, boolean _isRead, int _size)
  {
    id = _id;
    author = _author;
    subject = _subject;
    recipients = _recipients;
    ccRecipients = _ccRecipients;
    date = _date;
    charset = _charset;
    isRead = _isRead;
    size = _size;
  } // ctor

} // class CMessageHdr
