package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CNotification.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 21, 2008 11:06:48 AM CEST
*/

public final class CNotification implements org.omg.CORBA.portable.IDLEntity
{
  public boolean isDSNRequested = false;
  public boolean isMDNReadRequested = false;

  public CNotification ()
  {
  } // ctor

  public CNotification (boolean _isDSNRequested, boolean _isMDNReadRequested)
  {
    isDSNRequested = _isDSNRequested;
    isMDNReadRequested = _isMDNReadRequested;
  } // ctor

} // class CNotification
