package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CSecurity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Tuesday, May 13, 2008 4:03:40 PM CEST
*/

public final class CSecurity implements org.omg.CORBA.portable.IDLEntity
{
  public boolean isSigned = false;
  public boolean isCrypted = false;

  public CSecurity ()
  {
  } // ctor

  public CSecurity (boolean _isSigned, boolean _isCrypted)
  {
    isSigned = _isSigned;
    isCrypted = _isCrypted;
  } // ctor

} // class CSecurity
