package org.milimail.messageRemoteServiceAPI.stubs;

/**
* HeadersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Thursday, May 15, 2008 12:52:22 PM CEST
*/

public final class HeadersHolder implements org.omg.CORBA.portable.Streamable
{
  public Header value[] = null;

  public HeadersHolder ()
  {
  }

  public HeadersHolder (Header[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HeadersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HeadersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HeadersHelper.type ();
  }

}
