package org.milimail.messageRemoteServiceAPI.stubs;

/**
* HeaderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 21, 2008 11:06:48 AM CEST
*/

public final class HeaderHolder implements org.omg.CORBA.portable.Streamable
{
  public Header value = null;

  public HeaderHolder ()
  {
  }

  public HeaderHolder (Header initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HeaderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HeaderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HeaderHelper.type ();
  }

}
