package org.milimail.messageRemoteServiceAPI.stubs;

/**
* Header.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Thursday, June 12, 2008 11:49:38 AM CEST
*/

public final class Header implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public String value = null;

  public Header ()
  {
  } // ctor

  public Header (String _key, String _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class Header
