package org.milimail.messageRemoteServiceAPI.stubs;

/**
* InternalServerExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 21, 2008 11:06:48 AM CEST
*/

public final class InternalServerExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public InternalServerException value = null;

  public InternalServerExceptionHolder ()
  {
  }

  public InternalServerExceptionHolder (InternalServerException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InternalServerExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InternalServerExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InternalServerExceptionHelper.type ();
  }

}
