package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageBrowseService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message_remote_services/src/corba/Services.idl
* Friday, September 19, 2008 6:32:29 PM CEST
*/

public interface MessageBrowseService extends MessageBrowseServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageBrowseService
