package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageComposeService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Thursday, May 15, 2008 12:52:22 PM CEST
*/

public interface MessageComposeService extends MessageComposeServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageComposeService
