package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageComposeService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Friday, March 21, 2008 5:03:22 PM CET
*/

public interface MessageComposeService extends MessageComposeServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageComposeService
