package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageSendListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/ClientServices.idl
* Tuesday, March 25, 2008 3:23:05 PM CET
*/

public final class MessageSendListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public MessageSendListener value = null;

  public MessageSendListenerHolder ()
  {
  }

  public MessageSendListenerHolder (MessageSendListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MessageSendListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MessageSendListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MessageSendListenerHelper.type ();
  }

}
