package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageComposeService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 14, 2008 12:14:15 PM CEST
*/

public interface MessageComposeService extends MessageComposeServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageComposeService
