package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageSendListenerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/ClientServices.idl
* Tuesday, March 25, 2008 3:23:05 PM CET
*/

public abstract class MessageSendListenerPOA extends org.omg.PortableServer.Servant
 implements MessageSendListenerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("OnStop", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MessageSendListener/OnStop
       {
         String id = in.read_string ();
         boolean success = in.read_boolean ();
         this.OnStop (id, success);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MessageSendListener:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MessageSendListener _this() 
  {
    return MessageSendListenerHelper.narrow(
    super._this_object());
  }

  public MessageSendListener _this(org.omg.CORBA.ORB orb) 
  {
    return MessageSendListenerHelper.narrow(
    super._this_object(orb));
  }


} // class MessageSendListenerPOA
