package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageSendListener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/ClientServices.idl
* Tuesday, March 25, 2008 3:23:05 PM CET
*/

public interface MessageSendListener extends MessageSendListenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageSendListener
