package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageSendListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/ClientServices.idl
* Tuesday, March 25, 2008 3:23:05 PM CET
*/

public interface MessageSendListenerOperations 
{
  void OnStop (String id, boolean success);
} // interface MessageSendListenerOperations
