package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageComposeServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../MessageRemoteService/src/corba/Services.idl
* Wednesday, May 14, 2008 12:14:15 PM CEST
*/

public interface MessageComposeServiceOperations 
{
  void SendMessage (Account p_account, CMessage p_message, MessageSendListener p_listener, boolean openComposeWindowOnBadFormat) throws InternalServerException;
} // interface MessageComposeServiceOperations
