#!/bin/sh
# Print message count in a Postfix queue

usage() {
	echo "Usage:"
	echo "  $0 postfixMailName queueName"
	echo "    postfixMailName = mail_name value from main.cf"
	echo "    queueName = incoming|active|deferred"
	echo "  e.g.: $0 postfix0 deferred"
	exit
}

[ ! -z "$1" ] || usage
[ ! -z "$2" ] || usage
[ -d "/var/spool/$1" ] || usage
[ -d "/var/spool/$1/$2" ] || usage

find /var/spool/$1/$2 -type f | wc -l
