#!/bin/sh
# Update mail system monitoring data
# (launched by cron)

# Read settings
[ -r /etc/priority-email-gateway.conf ] || { echo "Settings not found in /etc/priority-email-gateway.conf!"; exit 1; }
. /etc/priority-email-gateway.conf
[ -n "$PRIORITY_COUNT" -a "$PRIORITY_COUNT" -gt 0 ] || { echo "Wrong priority count in /etc/priority-email-gateway.conf!"; exit 1; }

GET_QPSMTPD_COUNT="/usr/sbin/priority-email-gateway-getQpsmtpdCount"
GET_POSTFIX_QUEUE_COUNT="/usr/sbin/priority-email-gateway-getPostfixQueueCount"

mkdir -p $MONITORING_DIR

# Count Qpsmtpd instances
$GET_QPSMTPD_COUNT > $MONITORING_DIR/qpsmtpdCount

# Count messages in Postfix queues and store results in $MONITORING_DIR
for i in -frontend `seq 0 $(expr $PRIORITY_COUNT - 1)`; do
	$GET_POSTFIX_QUEUE_COUNT postfix$i incoming > $MONITORING_DIR/postfix$i-incoming
	$GET_POSTFIX_QUEUE_COUNT postfix$i active   > $MONITORING_DIR/postfix$i-active
	$GET_POSTFIX_QUEUE_COUNT postfix$i deferred > $MONITORING_DIR/postfix$i-deferred
	$GET_POSTFIX_QUEUE_COUNT postfix$i hold     > $MONITORING_DIR/postfix$i-hold
done
