package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Monday, January 26, 2009 3:56:37 PM CET
*/

public interface AccountServiceOperations 
{
  CAccount[] GetAllAccounts () throws CInternalServerException;
} // interface AccountServiceOperations
