package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Tuesday, December 16, 2008 12:19:22 PM CET
*/

public interface AccountService extends AccountServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AccountService
