package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Tuesday, December 9, 2008 4:49:24 PM CET
*/

public interface AccountServiceOperations 
{
  CAccount[] GetAllAccounts () throws CInternalServerException;
} // interface AccountServiceOperations
