package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Friday, December 5, 2008 5:38:41 PM CET
*/

public interface AccountService extends AccountServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AccountService
