package org.milimail.messageRemoteServiceAPI.stubs;

/**
* AccountServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Friday, December 5, 2008 3:26:53 PM CET
*/

public interface AccountServiceOperations 
{
  CAccount[] GetAllAccounts () throws CInternalServerException;
} // interface AccountServiceOperations
