package org.milimail.messageRemoteServiceAPI.stubs;

/**
* BodyListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Tuesday, December 9, 2008 4:49:24 PM CET
*/

public final class BodyListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public BodyListener value = null;

  public BodyListenerHolder ()
  {
  }

  public BodyListenerHolder (BodyListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BodyListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BodyListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BodyListenerHelper.type ();
  }

}
