package org.milimail.messageRemoteServiceAPI.stubs;

/**
* BrowseMessageListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Tuesday, December 9, 2008 4:34:42 PM CET
*/

public final class BrowseMessageListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public BrowseMessageListener value = null;

  public BrowseMessageListenerHolder ()
  {
  }

  public BrowseMessageListenerHolder (BrowseMessageListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BrowseMessageListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BrowseMessageListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BrowseMessageListenerHelper.type ();
  }

}
