package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CAttachmentsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Tuesday, December 16, 2008 12:19:22 PM CET
*/

public final class CAttachmentsHolder implements org.omg.CORBA.portable.Streamable
{
  public CAttachment value[] = null;

  public CAttachmentsHolder ()
  {
  }

  public CAttachmentsHolder (CAttachment[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CAttachmentsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CAttachmentsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CAttachmentsHelper.type ();
  }

}
