package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CDSNTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Friday, December 5, 2008 3:26:53 PM CET
*/

abstract public class CDSNTypeHelper
{
  private static String  _id = "IDL:CDSNType:1.0";

  public static void insert (org.omg.CORBA.Any a, CDSNType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CDSNType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[0] = new org.omg.CORBA.StructMember (
            "isReturnFullHDRRequested",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[1] = new org.omg.CORBA.StructMember (
            "isOnSuccessRequested",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[2] = new org.omg.CORBA.StructMember (
            "isOnFailureRequested",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "isOnDelayRequested",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[4] = new org.omg.CORBA.StructMember (
            "isNeverRequested",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CDSNTypeHelper.id (), "CDSNType", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CDSNType read (org.omg.CORBA.portable.InputStream istream)
  {
    CDSNType value = new CDSNType ();
    value.isReturnFullHDRRequested = istream.read_boolean ();
    value.isOnSuccessRequested = istream.read_boolean ();
    value.isOnFailureRequested = istream.read_boolean ();
    value.isOnDelayRequested = istream.read_boolean ();
    value.isNeverRequested = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CDSNType value)
  {
    ostream.write_boolean (value.isReturnFullHDRRequested);
    ostream.write_boolean (value.isOnSuccessRequested);
    ostream.write_boolean (value.isOnFailureRequested);
    ostream.write_boolean (value.isOnDelayRequested);
    ostream.write_boolean (value.isNeverRequested);
  }

}
