package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CFolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Monday, January 26, 2009 3:56:37 PM CET
*/

public final class CFolder implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String uri = null;

  public CFolder ()
  {
  } // ctor

  public CFolder (String _name, String _uri)
  {
    name = _name;
    uri = _uri;
  } // ctor

} // class CFolder
