package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CMessageHdr.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Monday, January 26, 2009 3:56:37 PM CET
*/

public final class CMessageHdr implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public int key = (int)0;
  public String uri = null;
  public String author = null;
  public String subject = null;
  public String recipients[] = null;
  public String ccRecipients[] = null;
  public String date = null;
  public String charset = null;
  public boolean isRead = false;
  public int size = (int)0;

  public CMessageHdr ()
  {
  } // ctor

  public CMessageHdr (String _id, int _key, String _uri, String _author, String _subject, String[] _recipients, String[] _ccRecipients, String _date, String _charset, boolean _isRead, int _size)
  {
    id = _id;
    key = _key;
    uri = _uri;
    author = _author;
    subject = _subject;
    recipients = _recipients;
    ccRecipients = _ccRecipients;
    date = _date;
    charset = _charset;
    isRead = _isRead;
    size = _size;
  } // ctor

} // class CMessageHdr
