package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CNotification.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Friday, December 12, 2008 12:37:19 PM CET
*/

public final class CNotification implements org.omg.CORBA.portable.IDLEntity
{
  public boolean isDSNRequested = false;
  public CDSNType DSNType = null;
  public boolean isMDNReadRequested = false;

  public CNotification ()
  {
  } // ctor

  public CNotification (boolean _isDSNRequested, CDSNType _DSNType, boolean _isMDNReadRequested)
  {
    isDSNRequested = _isDSNRequested;
    DSNType = _DSNType;
    isMDNReadRequested = _isMDNReadRequested;
  } // ctor

} // class CNotification
