package org.milimail.messageRemoteServiceAPI.stubs;

/**
* HeadersListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Tuesday, December 9, 2008 4:49:24 PM CET
*/

public interface HeadersListenerOperations 
{
  void OnLoad (CHeader[] p_headers);
} // interface HeadersListenerOperations
