package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageComposeService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Friday, December 12, 2008 12:37:19 PM CET
*/

public interface MessageComposeService extends MessageComposeServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageComposeService
