package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageComposeServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Monday, January 26, 2009 3:56:37 PM CET
*/

public interface MessageComposeServiceOperations 
{
  void SendMessage (CAccount p_account, CMessage p_message, MessageSendListener p_listener, boolean openComposeWindowOnBadFormat) throws CInternalServerException;
} // interface MessageComposeServiceOperations
