package org.milimail.messageRemoteServiceAPI.stubs;

/**
* octetSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Monday, January 26, 2009 3:56:38 PM CET
*/

public final class octetSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public octetSeqHolder ()
  {
  }

  public octetSeqHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = octetSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    octetSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return octetSeqHelper.type ();
  }

}
