package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceMessageListener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Tuesday, December 9, 2008 4:34:42 PM CET
*/

public interface SourceMessageListener extends SourceMessageListenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SourceMessageListener
