package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceMessageListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Friday, December 5, 2008 3:26:54 PM CET
*/

public interface SourceMessageListenerOperations 
{
  void OnLoad (String source);
} // interface SourceMessageListenerOperations
