package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceMessageListener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Monday, December 8, 2008 11:31:29 AM CET
*/

public interface SourceMessageListener extends SourceMessageListenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SourceMessageListener
