package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceMessageListener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Friday, December 5, 2008 3:26:54 PM CET
*/

public interface SourceMessageListener extends SourceMessageListenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SourceMessageListener
