package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceListener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Tuesday, December 16, 2008 12:19:23 PM CET
*/

public interface SourceListener extends SourceListenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SourceListener
