package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceMessageListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Tuesday, December 9, 2008 4:34:42 PM CET
*/

public interface SourceMessageListenerOperations 
{
  void OnLoad (String source, CHeader[] p_headers);
} // interface SourceMessageListenerOperations
