package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Tuesday, December 9, 2008 4:49:24 PM CET
*/

public interface SourceListenerOperations 
{
  void OnLoad (String source);
} // interface SourceListenerOperations
