package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Friday, December 12, 2008 12:37:19 PM CET
*/

public interface SourceListenerOperations 
{
  void OnLoad (String source);
} // interface SourceListenerOperations
