package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceMessageListenerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Monday, December 8, 2008 11:31:29 AM CET
*/

public abstract class SourceMessageListenerPOA extends org.omg.PortableServer.Servant
 implements SourceMessageListenerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("OnLoad", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SourceMessageListener/OnLoad
       {
         String source = in.read_string ();
         this.OnLoad (source);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SourceMessageListener:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SourceMessageListener _this() 
  {
    return SourceMessageListenerHelper.narrow(
    super._this_object());
  }

  public SourceMessageListener _this(org.omg.CORBA.ORB orb) 
  {
    return SourceMessageListenerHelper.narrow(
    super._this_object(orb));
  }


} // class SourceMessageListenerPOA
