package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceMessageListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Monday, December 8, 2008 11:31:29 AM CET
*/

public interface SourceMessageListenerOperations 
{
  void OnLoad (String source);
} // interface SourceMessageListenerOperations
