# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /home/oparnier/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games
