package org.milimail.messageRemoteServiceAPI.stubs;

/**
* CAttachmentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Monday, January 26, 2009 3:56:37 PM CET
*/

public final class CAttachmentHolder implements org.omg.CORBA.portable.Streamable
{
  public CAttachment value = null;

  public CAttachmentHolder ()
  {
  }

  public CAttachmentHolder (CAttachment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CAttachmentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CAttachmentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CAttachmentHelper.type ();
  }

}
