package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageBrowseServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Monday, January 26, 2009 3:56:37 PM CET
*/

public interface MessageBrowseServiceOperations 
{
  void GetRootFolder (CAccount p_account, CFolderHolder p_rootFolder) throws CInternalServerException;
  void GetLocalFolder (CFolderHolder p_localFolder) throws CInternalServerException;
  void GetAllFolders (CFolder p_rootFolder, CFoldersHolder p_folders) throws CInternalServerException;
  void GetMessageHdrs (CFolder p_folder, CMessageHdrsHolder p_messageHdrs) throws CInternalServerException;
  void GetSource (CMessageHdr p_messageHdr, SourceListener p_sourceListener) throws CInternalServerException;
  void GetDecryptedSource (CMessageHdr p_messageHdr, SourceListener p_sourceListener) throws CInternalServerException;
  void GetNewMessages (CFolder p_Folder) throws CInternalServerException;
} // interface MessageBrowseServiceOperations
