package org.milimail.messageRemoteServiceAPI.stubs;

/**
* MessageComposeService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/Services.idl
* Monday, January 26, 2009 3:56:37 PM CET
*/

public interface MessageComposeService extends MessageComposeServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageComposeService
