package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Monday, January 26, 2009 3:56:38 PM CET
*/

public final class SourceListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public SourceListener value = null;

  public SourceListenerHolder ()
  {
  }

  public SourceListenerHolder (SourceListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SourceListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SourceListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SourceListenerHelper.type ();
  }

}
