package org.milimail.messageRemoteServiceAPI.stubs;

/**
* SourceListener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../message-remote-services/src/corba/ClientServices.idl
* Monday, January 26, 2009 3:56:38 PM CET
*/

public interface SourceListener extends SourceListenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SourceListener
